#!/bin/env python3

#all data plotted here was generated by running:
# ./find_memory_footprint.sh
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import glob
from natsort import humansorted

data_files = glob.glob("./memory_footprints_*.csv")

df = pd.DataFrame()

for data_file in data_files:
    memory = pd.read_csv(data_file)
    data_file = data_file.replace('.csv','')
    if "_with_threading" in data_file:
        continue
    x = data_file.split('_')
    device = x[2]
    device = device.split('-')[1]
    type_of_run = ""
    if x[3] == "with":
        type_of_run = "Yes"
    else:
        type_of_run = "No"
    df = pd.concat([df,pd.DataFrame({"GPU Version:": device, "Uses Backpropagation?" : type_of_run, "n_gen_events": memory.n_gen_events, "Peak Memory Used":memory.memory})])

df["Peak Memory Used"] = df["Peak Memory Used"]*1E-09  # convert from bytes to gigabytes
df["n_gen_events"] = df["n_gen_events"]/1000000  # convert from bytes to gigabytes


fig, ax = plt.subplots(figsize=(10,7.5))
lp = sns.lineplot(data=df, x="n_gen_events", y="Peak Memory Used", hue="GPU Version:", style="Uses Backpropagation?")
#sort the legend labels
#handles, labels = lp.get_legend_handles_labels()
#labels, handles = zip(*humansorted(zip(labels, handles)))
#plot it
#plt.legend(handles, labels, title='# Events Showing Memory Constraints',title_fontsize=18)
#plt.title('Generating 1M Events with LOITS',fontsize=25)
#plt.tick_params(labelsize=12)
plt.legend(title_fontsize=18)
lp.set_xlabel("# Events (Millions)",fontsize=18)
lp.set_ylabel("Peak Memory Used (GBs)",fontsize=18)
fig = lp.get_figure()
fig.savefig("peak_memory.pdf") 
fig.savefig("peak_memory.png") 
